name: CI/CD

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@main

      - name: Set up JDK 25
        uses: actions/setup-java@main
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Update Latest Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: latest
          files: target/BukkitAI.jar
          prerelease: true
          name: Latest Development Build
          body: "Automatic build from latest commit."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
